### ISSUE TITLE
Is `v1.0.7` the latest release?

### ISSUE THREAD

**Issue by ZhongRuoyu** [HDT3213/rdb#14]
Hi! [Homebrew](https://github.com/Homebrew/brew) maintainer here. We noticed that `v1.0.7` was tagged, but is not yet marked as latest on the repo's [releases page](https://github.com/HDT3213/rdb/releases). I'm filing this issue to confirm if the release is ready to be marked as latest, so that we can go ahead and ship it. Thanks!

**Comment by HDT3213** [comment]
v1.0.7​ only updated the API, and the terminal tool has not changed, so homebrew package does not need to be updated.

Thanks for asking
________________________________
发件人: Ruoyu Zhong ***@***.***>
发送时间: 2023年4月9日 13:59
收件人: HDT3213/rdb ***@***.***>
抄送: Subscribed ***@***.***>
主题: [HDT3213/rdb] Is `v1.0.7` the latest release? (Issue #14)


Hi! Homebrew<https://github.com/Homebrew/brew> maintainer here. We noticed that v1.0.7 was tagged, but is not yet marked as latest on the repo's releases page<https://github.com/HDT3213/rdb/releases>. I'm filing this issue to confirm if the release is ready to be marked as latest, so that we can go ahead and ship it. Thanks!

**Comment by ZhongRuoyu** [comment]
Thanks @HDT3213. However, in that case, I don't see any reason against shipping this latest release. (Although the CLI tool will probably be the same.) So we decided to update `rdb` to 1.0.7 anyway.
