### ISSUE TITLE
Possible to try and skip malformed entries?

### ISSUE THREAD

**Issue by ptaoussanis** [HDT3213/rdb#15]
Hi, and thank you so much for this wonderful tool!

I have a question-

I have an RDB dump file that has at least one entry that seems to be invalid.
`redis-check-rdb dump.rdb` shows an error:

```
[offset 0] Checking RDB file dump.rdb
[offset 26] AUX FIELD redis-ver = '5.0.8'
[offset 40] AUX FIELD redis-bits = '64'
[offset 52] AUX FIELD ctime = '1681088401'
[offset 67] AUX FIELD used-mem = '1359262528'
[offset 83] AUX FIELD aof-preamble = '0'
[offset 85] Selecting DB ID 0
--- RDB ERROR DETECTED ---
[offset 51432] Internal error in RDB reading offset 0, function at rdb.c:2080 -> Ziplist integrity check failed.
[additional info] While doing: read-object-value
[additional info] Reading key 'badkey-x'
[additional info] Reading type 14 (quicklist)
[info] 87 keys read
[info] 1 expires
[info] 0 already expired
46161:C 10 Apr 2023 11:42:54.008 # Terminating server after rdb file reading failure.
```

I'm hoping to try to use or modify your tool to see if it might be possible to skip this `badkey-x`, and try to save as much of the rest of the data in the rdb file as possible.

When I try `./rdb -c aof -o dump.aof dump.rdb` I get the following error:
`error: panic: runtime error: slice bounds out of range [:10] with capacity 0`

I'm currently digging into the source code to try better understand how parsing works and if it might be possible to try skip over a broken entry.

In case you have any advice on if this might be possible, or how to do it - I'd really appreciate your guidance.

Thank you again!

**Comment by HDT3213** [comment]
First of All, thank you for your support.

Based on the information I have obtained so far, it seems that a ziplist in the quicklist is broken. You can confirm this by checking the stacktrace when the panic occurred.

If that's the case, we are very lucky because the ziplist in the RDB file is wrapped in a string. (See: [readZipList](https://github.com/HDT3213/rdb/blob/4b02fc94f55a66886e5ad0199b1c28aa38371550/core/ziplist.go)). You could modify the readZipList function to ignore errors and panics encountered after dec.readString(), so that only the corrupted ziplist will be discarded and other data will be preserved.

Anyway, please check the stacktrace first to confirm if readZipList panicked.

**Comment by HDT3213** [comment]
Hope it's just some bits reversed, it would be very troublesome if some bytes were mixed in or some were missing

**Comment by ptaoussanis** [comment]
I believe it worked!

[This](https://github.com/HDT3213/rdb/blob/92410bbe9c92a875f3da6b3af6635ddd962a0b26/core/ziplist.go#L17) was the precise line that was throwing.

I added a line of code before that:
```
if len(buf) < 10 { return nil, nil }
```

Which allowed `./rdb -c aof -o dump.aof dump.rdb` to successfully complete.

The resulting `.aof` file could be successfully loaded into Redis.
I'm still trying to investigate exactly how much data needed to be dropped, but this is already a much better outcome than losing the whole dump.

Again, thank you so much for your very quick help on this - and for the amazing tool 🙏

**Comment by HDT3213** [comment]
I am glad to help you solve the problem
